//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webApp1.Dbprofile
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEE2
    {
        public int ID { get; set; }
        public string F_NAME { get; set; }
        public string L_NAME { get; set; }
        public Nullable<int> SALARY { get; set; }
        public string DEPARTMENT_NAME { get; set; }
        public string GENDER { get; set; }
        public Nullable<int> DEPARTMENT_NO { get; set; }
    }
}
